### PR TITLE
Fix jcenter

### PR DESCRIPTION
**Pull request by mptr**
Bumped to RN 66 and Android 31
Removed QR scanner to be able to build app at the moment.

### CODE REVIEW

**Comment by mptr** [comment]
You will need to reinstall Android tools. To do so:
```sh
adb kill-server
rm -r ~/Android
vi ~/.bashrc # at end of file remove all lines associated with Java, Android or React
# clone the repo & cd there
./install
yarn cache clean && rm -r ./node_modules
yarn install
# dependencies now ready
yarn android 
yarn start
```

**Comment by mptr** [comment]
TODO: Test iOS @lmaos-txt

**Comment by lmaos-code** [comment]
@mptr iOS should be fine. Will test soon

**Comment by lmaos-code** [comment]
Did not test Android
iOS works now!
@mptr integrate?

**Review by lmaos-code — APPROVED** [review]
👍🏾

**Comment by mptr** [comment]
throws `Frame Processor threw an error: Value is undefined, expected an Object` if camera active.

**Pull request merged**
